#include<stdio.h>
#include<conio.h>
#include<math.h>
void main()
{
int col,row,i,len;
clrscr();
col=22;row=1,len=27;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
    {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Û");

     }


col=22;row=1,len=51;
gotoxy(col,row);
for(i=row;i<=row+len;i++)
    {
     gotoxy(col,i);
     textcolor(BLUE);
     cprintf("Û");

     }


col=49;row=1,len=24;
gotoxy(col,row);
for(i=row;i<=row+len;i++)
    {
     gotoxy(col,i);
     textcolor(BLUE);
     cprintf("Û");

     }



col=24;row=2,len=23;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
    {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Ü");

     }


col=24;row=10,len=23;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
    {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Ü");

     }

col=24;row=3,len=7;
gotoxy(col,row);
for(i=row;i<=row+len;i++)
    {
     gotoxy(col,i);
     textcolor(BLUE);
     cprintf("Û");

     }

col=47;row=3,len=7;
gotoxy(col,row);
for(i=row;i<=row+len;i++)
    {
     gotoxy(col,i);
     textcolor(BLUE);
     cprintf("Û");

     }



col=24;row=11,len=23;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
    {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("±");

     }

col=24;row=24,len=23;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
    {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Ä");

     }

col=24;row=12,len=23;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
    {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Ä");

     }
col=24;row=18,len=23;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
    {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Ä");

     }


col=24;row=22,len=23;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
    {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Ä");

     }


col=24;row=20,len=23;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
    {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Ä");

     }

col=24;row=18,len=23;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
    {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Ä");

     }

col=24;row=16,len=23;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
    {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Ä");

     }

col=24;row=14,len=23;
gotoxy(col,row);
for(i=col;i<=col+len;i++)
    {
     gotoxy(i,row);
     textcolor(BLUE);
     cprintf("Ä");

     }




col=23;row=12,len=12;
gotoxy(col,row);
for(i=row;i<=row+len;i++)
    {
     gotoxy(col,i);
     textcolor(BLUE);
     cprintf("³");

     }

col=48;row=12,len=12;
gotoxy(col,row);
for(i=row;i<=row+len;i++)
    {
     gotoxy(col,i);
     textcolor(BLUE);
     cprintf("³");

     }

col=36;row=12,len=12;
gotoxy(col,row);
for(i=row;i<=row+len;i++)
    {
     gotoxy(col,i);
     textcolor(BLUE);
     cprintf("³");

     }

col=30;row=12,len=12;
gotoxy(col,row);
for(i=row;i<=row+len;i++)
    {
     gotoxy(col,i);
     textcolor(BLUE);
     cprintf("³");

     }

col=42;row=12,len=12;
gotoxy(col,row);
for(i=row;i<=row+len;i++)
    {
     gotoxy(col,i);
     textcolor(BLUE);
     cprintf("³");

     }


col=26;row=23;//len=23;
gotoxy(col,row);
//for(i=col;i<=col+len;i++)
    //{
    //gotoxy(i,row);
     textcolor(WHITE);
     cprintf("0");

    //}
col=33;row=23;
gotoxy(col,row);
textcolor(WHITE);
cprintf(".");

col=39;row=23;
gotoxy(col,row);
textcolor(WHITE);
cprintf("=");

col=26;row=17;
gotoxy(col,row);
textcolor(WHITE);
cprintf("7");

col=33;row=17;
gotoxy(col,row);
textcolor(WHITE);
cprintf("8");

col=39;row=17;
gotoxy(col,row);
textcolor(WHITE);
cprintf("9");

col=26;row=19;
gotoxy(col,row);
textcolor(WHITE);
cprintf("4");

col=33;row=19;
gotoxy(col,row);
textcolor(WHITE);
cprintf("5");

col=39;row=19;
gotoxy(col,row);
textcolor(WHITE);
cprintf("6");

col=26;row=21;
gotoxy(col,row);
textcolor(WHITE);
cprintf("1");

col=33;row=21;
gotoxy(col,row);
textcolor(WHITE);
cprintf("2");

col=39;row=21;
gotoxy(col,row);
textcolor(WHITE);
cprintf("3");

col=45;row=23;
gotoxy(col,row);
textcolor(WHITE);
cprintf("+");


col=45;row=21;
gotoxy(col,row);
textcolor(WHITE);
cprintf("-");


col=45;row=19;
gotoxy(col,row);
textcolor(WHITE);
cprintf("*");

col=45;row=17;
gotoxy(col,row);
textcolor(WHITE);
cprintf("/");

col=45;row=15;
gotoxy(col,row);
textcolor(WHITE);
cprintf("%");

col=45;row=13;
gotoxy(col,row);
textcolor(WHITE);
cprintf("^");

col=33;row=15;
gotoxy(col,row);
textcolor(WHITE);
cprintf("(");

col=39;row=15;
gotoxy(col,row);
textcolor(WHITE);
cprintf(")");


col=26;row=15;
gotoxy(col,row);
textcolor(WHITE);
cprintf("x");

col=25;row=13;
gotoxy(col,row);
textcolor(WHITE);
cprintf("log");

col=33;row=13;
gotoxy(col,row);
textcolor(WHITE);
cprintf("i");

col=39;row=13;
gotoxy(col,row);
textcolor(WHITE);
cprintf("pi");

col=25;row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf(" ");


	     int a,b,c,n;
	     //int y=sqrt(-1);
	   // clrscr();
	    //cprintf("enter two numbers");

	    /*col=26;row=4;
	    gotoxy(col,row);
	    textcolor(GREEN);
	    //cprintf(" ");
	    cprintf("a and b");*/

	    col=26;row=4;
	    gotoxy(col,row);
	    //textcolor(GREEN);
	    //cprintf(" ");
	    scanf("%d%s%d",&a,&n,&b);

	     col=26;row=9;
	    gotoxy(col,row);
	    textcolor(GREEN);
	    //cprintf(" ")

	   switch(n)
		 {
		case'+':
		c=a+b;
		cprintf("%d",c);
		break;

		case'-':
		c=a-b;
		cprintf("%d",c);
		break;

		case'*':
		c=a*b;
		cprintf("%d",c);
		break;

		case'/':
		c=a/b;
		cprintf("%d",c);
		break;


		case'%':
		c=a%b;
		cprintf("%d",c);
		break;

		case'^':
		c=pow(a,b);
		cprintf("%d",c);
		break;

		/*case'e':
		c=a;
		cprintf("%d",c);
		break;

		/*case'/':
		c=a/b;
		cprintf("%d",c);
		break;*/

		default:
		cprintf("Syntax Error");
		}


getch();
}